name: Release
on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:
jobs:
  lint-python:
    name: Run Python lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-python.yml@master

  download-openssl:
    name: Download OpenSSL-Win32/64
    needs:
      - lint-python
    runs-on: windows-latest
    strategy:
      matrix:
        openssl:
          - url: "https://www.firedaemon.com/download-firedaemon-openssl-1.1.1-zip"
            path: "openssl-1.1\\"
            output: "openssl1"
          - url: "https://www.firedaemon.com/download-firedaemon-openssl-3-6-zip"
            path: ""
            output: "openssl3"
    steps:
      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v3
        with:
          path: ${{ matrix.openssl.output }}-*
          key: ${{ runner.os }}-openssl-${{ matrix.openssl.url }}
      - name: Unpacking OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          mkdir ${{ matrix.openssl.output }}
          cd ${{ matrix.openssl.output }}
          certutil.exe -urlcache -split -f "${{ matrix.openssl.url }}" openssl.zip
          7z x openssl.zip
          xcopy /S "${{ matrix.openssl.path }}x86\include" ..\${{ matrix.openssl.output }}-win32\include\
          xcopy /S "${{ matrix.openssl.path }}x86\lib" ..\${{ matrix.openssl.output }}-win32\lib\
          xcopy /S "${{ matrix.openssl.path }}x64\include" ..\${{ matrix.openssl.output }}-win64\include\
          xcopy /S "${{ matrix.openssl.path }}x64\lib" ..\${{ matrix.openssl.output }}-win64\lib\
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openssl-win-${{ matrix.openssl.output }}
          path: openssl?-win*/
          if-no-files-found: error

  build-poetry:
    name: Build Python package
    needs:
      - lint-python
      - download-openssl
    uses: kuba2k2/kuba2k2/.github/workflows/build-poetry.yml@master
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        architecture: ["x86", "x64"]
        build:
          - runs-on: windows-latest
            openssl: "openssl-*"
            format: "wheel"
            test-fixup: "python sslpsk3_fixup.py"
        include:
          - python: "3.12"
            build:
              runs-on: ubuntu-latest
              openssl: ""
              format: "sdist"
              test-fixup: ""
          - python: "3.13"
            build:
              runs-on: ubuntu-latest
              openssl: ""
              format: "sdist"
              test-fixup: ""
    with:
      runs-on: ${{ matrix.build.runs-on }}
      input-artifact: ${{ matrix.build.openssl }}
      input-path: "."
      python-version: ${{ matrix.python }}
      architecture: ${{ matrix.architecture }}
      args: --format=${{ matrix.build.format }}
      post-build: |
        python -m pip install pytest
        pip install -e .
        ${{ matrix.build.test-fixup }}
        cd tests
        python -m pytest -s
      files: |
        dist/*.whl
        dist/*.tar.gz
      output-artifact: sslpsk3-${{ matrix.python }}-${{ matrix.architecture }}-${{ matrix.build.format }}

  publish-pypi:
    name: Publish PyPI package
    if: ${{ github.event_name != 'workflow_dispatch' }}
    needs:
      - build-poetry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: sslpsk3-*
          path: dist/
          merge-multiple: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: python -m pip install --upgrade poetry
      - name: Publish PyPI package
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

  gh-release:
    name: Publish GitHub release
    if: ${{ github.event_name != 'workflow_dispatch' }}
    needs:
      - build-poetry
    uses: kuba2k2/kuba2k2/.github/workflows/gh-release.yml@master
    permissions:
      contents: write
    with:
      artifact: sslpsk3-*
